### ISSUE TITLE
All Entities Unavailable, Errors in Log

### ISSUE THREAD

**Issue by mediacutlet** [natekspencer/hacs-pentair#10]
This integration was working great for over a month but this weekend all the entities have gone offline. I've tried a few basic troubleshooting things including deleting the integration and reconfiguring with the same result. Not sure if something changed on the Pentair side. Error log included below. Thank you for the time you've put into this! Hopefully this is an easy fix. I haven't upgraded to 2024.6 or changed anything significant on my end to my knowledge.

HA Version: 2024.5.3
Pentair Home Version: 0.2.0

`Logger: homeassistant
Source: custom_components/pentair_cloud/helpers.py:21
integration: Pentair Home ([documentation](https://github.com/natekspencer/hacs-pentair), [issues](https://github.com/natekspencer/hacs-pentair/issues))
First occurred: June 15, 2024 at 3:18:31 PM (2000 occurrences)
Last logged: 8:01:43 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 414, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 492, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1009, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1015, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 296, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/pentair_cloud/binary_sensor.py", line 131, in is_on
    return self.entity_description.is_on(self.get_device())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pentair_cloud/binary_sensor.py", line 42, in <lambda>
    is_on=lambda data: get_field_value("s25", data),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pentair_cloud/helpers.py", line 21, in get_field_value
    name, value = get_api_field_name_and_value(key, data["fields"][key])
                                                    ~~~~~~~~~~~~~~^^^^^
KeyError: 's25'`

**Comment by natekspencer** [comment]
Can you also download diagnostics and include that?

**Comment by mediacutlet** [comment]
Sure! Here is the diagnostic file as well as a debug log had recording during an attempt to reload the integration. Thanks again for looking into it! I try not to rely too heavily on experimentail HACS components but its been wonderful having this data on my pool dashboard. Cheers mate.

[home-assistant_pentair_cloud_2024-06-16T17-19-36.740Z.log](https://github.com/user-attachments/files/15859148/home-assistant_pentair_cloud_2024-06-16T17-19-36.740Z.log)
[config_entry-pentair_cloud-e8c4675f178dbb45a4355dc4417852a6.json](https://github.com/user-attachments/files/15859149/config_entry-pentair_cloud-e8c4675f178dbb45a4355dc4417852a6.json)

_Updated to HA 2024.6.3 today by the way and the error is the same as it was on 2024.5.3_

**Comment by natekspencer** [comment]
> [config_entry-pentair_cloud-e8c4675f178dbb45a4355dc4417852a6.json](https://github.com/user-attachments/files/15859149/config_entry-pentair_cloud-e8c4675f178dbb45a4355dc4417852a6.json)

Well, bad news, no fields data is being returned for your device now via the existing endpoint: `"fields": {}`.

It's possible this is temporary, or that Pentair has migrated off of that endpoint entirely for reporting data for your device.

**Comment by mediacutlet** [comment]
Ah bummer. Well, it was fun while it lasted! Thanks for looking into it.

**Comment by alefchak** [comment]
I did some digging into this, and it looks like the device fields are accessible at another endpoint, `device/device-service/user/device/<deviceID>`

**Comment by natekspencer** [comment]
@alefchak would you be able to post the response from that for your device so I can see how they compare?

**Comment by alefchak** [comment]
> @alefchak would you be able to post the response from that for your device so I can see how they compare?

Attached output from that endpoint, removed all my personal info (I hope...).

[output.json](https://github.com/user-attachments/files/16575639/output.json)

**Comment by JustDFB** [comment]
Hi all,
I would love to see this integrated brought back to life! If there is anything I can do in terms of testing or providing data please let me know.
Thanks in advance 😊

**Comment by chansearrington** [comment]
I just got two new Pentair pumps and they don’t seem to work with this integration anymore.

As the original post says, they show up, but don’t pull any info / control

Diagnostic attached

[config_entry-pentair_cloud-01JVDPPVS5M5JKRC0PVVQV56KS.json](https://github.com/user-attachments/files/20269873/config_entry-pentair_cloud-01JVDPPVS5M5JKRC0PVVQV56KS.json)

**Comment by chansearrington** [comment]
I see another user @jgemkow has forked this and supposedly resolved it via his commit notes, but I can't get it to work for me on my setup. Has anyone else tried it?

https://github.com/JGemkow/hacs-pentair

**Comment by traveler2100** [comment]
I have new pumps also and I have not been able to get this integration to report any values and I cannot get the fork to load.  I'm surprised as popular as Pentair pumps are, that there is not a working solution.

**Comment by natekspencer** [comment]
Apologies for the super long delay in any additions here. I only have a salt level sensor, so it's difficult to try and get around to working on this 😅

In other news, I've created a beta release (https://github.com/natekspencer/hacs-pentair/releases/tag/0.3.0b0) that attempts to pull in more data from the device specific endpoint. If nothing else, it should at least give more diagnostic data.
